services:

  postgres:
    image: postgres:15
    container_name: energy_postgres
    restart: always

    environment:
      POSTGRES_USER: energy_user
      POSTGRES_PASSWORD: energy_pass
      POSTGRES_DB: energy_db

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


  backend:
    build: .
    container_name: energy_backend
    restart: always

    depends_on:
      - postgres

    ports:
      - "3000:3000"

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: energy_user
      DB_PASS: energy_pass
      DB_NAME: energy_db

    command: npm run start:prod


volumes:
  pgdata:
